Repository codesupport/website-frontend, pull requests merged in 2020-01, with the labels that each got.

#5 Search Bar and Category Filter on Resources Page
  src/components/molecules/Card.js
  src/components/pages/Resources.js
  src/config.js
  src/css/pages/resources.css
  src/css/style.css
Labels: enhancement

#7 Added Python, Software and CSharp resource categories.
  src/config.js
Labels: enhancement, page: resources

#8 Added the ability to filter between free, paid and all resources.
  src/components/pages/Resources.js
  src/css/pages/resources.css
Labels: enhancement, page: resources

#10 Add missing resource categories to the config
  src/config.js
Labels: enhancement

#11 Keep a constant copy of the resource state
  src/components/pages/Resources.js
Labels: enhancement, page: resources

#14 Added SignUpForm
  src/components/atoms/SubmitButton.js
  src/components/molecules/LabelWithInput.js
  src/components/molecules/Navigation.js
  src/components/organisms/SignUpForm.js
  src/components/templates/ModalContainer.js
  src/css/atoms/submitbutton.css
  src/css/molecules/labelwithinput.css
  src/css/organisms/signupform.css
  src/css/style.css
  src/css/templates/modalcontainer.css
Labels: enhancement

#15 Added CODEOWNERS and added useful information to the README.
  .github/CODEOWNERS
  README.md
  package.json
Labels: documentation

#16 Profile Page
  README.md
  package-lock.json
  package.json
  src/__tests__/components/molecules/GitHubRepositoriesFeed.js
  src/__tests__/components/molecules/ProfileFeed.js
  src/__tests__/components/molecules/ShowcaseProjectsFeed.js
  src/components/atoms/Tag.js
  src/components/molecules/Card.js
  src/components/molecules/GitHubRepositoriesFeed.js
  src/components/molecules/ProfileFeed.js
  src/components/molecules/ShowcaseProjectsFeed.js
  src/components/organisms/ProfileHeader.js
  src/components/pages/Profile.js
  src/config.js
  src/css/atoms/tag.css
  src/css/molecules/card.css
  src/css/molecules/githubrepositoriesfeed.css
  src/css/organisms/profileheader.css
  src/css/pages/profile.css
  src/css/style.css
  src/index.js
Labels: enhancement, page: profile

#18 UserProfileService
  .gitignore
  README.md
  package-lock.json
  package.json
  src/__tests__/components/molecules/GitHubRepositoriesFeed.js
  src/__tests__/components/molecules/ShowcaseProjectsFeed.js
  src/__tests__/components/pages/ProfilePageTest.js
  src/__tests__/services/UserProfileServiceTest.js
  src/components/molecules/GitHubRepositoriesFeed.js
  src/components/molecules/ShowcaseProjectsFeed.js
  src/components/organisms/ProfileHeader.js
  src/components/pages/Profile.js
  src/helpers/redirect.js
  src/services/UserProfileService.js
Labels: enhancement, page: profile, service: UserProfileService

#19 Add GitHubService
  src/__tests__/services/GitHubServiceTest.js
  src/components/molecules/GitHubRepositoriesFeed.js
  src/services/GitHubService.js
Labels: enhancement, service: GitHubService

#22 Codacy Coverage
  .github/workflows/main.yml
  README.md
  package-lock.json
  package.json
Labels: CI, enhancement

#25 Add <ErrorTemplate />
  src/components/molecules/GitHubRepositoriesFeed.js
  src/components/pages/Profile.js
  src/components/pages/Resources.js
  src/components/templates/ErrorTemplate.js
  src/css/templates/errortemplate.css
  src/services/GitHubService.js
  src/services/UserProfileService.js
Labels: enhancement

#27 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#24 Fix issues raised by Codacy.
  src/components/atoms/SubmitButton.js
  src/components/atoms/Tag.js
  src/components/molecules/Card.js
  src/components/molecules/GitHubRepositoriesFeed.js
  src/components/organisms/SignUpForm.js
  src/components/pages/Resources.js
  src/components/templates/ModalContainer.js
Labels: cleanup

#28 Resources Changes
  src/__tests__/components/pages/Resources.js
  src/__tests__/helpers/sortArrayByTest.js
  src/__tests__/services/ResourcesServiceTest.js
  src/components/pages/Resources.js
  src/helpers/sortArrayBy.js
  src/services/ResourcesService.js
Labels: cleanup, enhancement, page: resources, service: ResourcesService
